// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCccpNsKl6vgYoCsiG3B7lT1FjuvKUQpbQ',
    appId: '1:328461664020:web:ccc94fb6d0eaa8222d0c01',
    messagingSenderId: '328461664020',
    projectId: 'flutter-tik-tok-clone-hoo',
    authDomain: 'flutter-tik-tok-clone-hoo.firebaseapp.com',
    storageBucket: 'flutter-tik-tok-clone-hoo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOa2kvcPGVteE-x1uXLENZuj4rqtv8B5I',
    appId: '1:328461664020:android:2b4dc9bc74e781c22d0c01',
    messagingSenderId: '328461664020',
    projectId: 'flutter-tik-tok-clone-hoo',
    storageBucket: 'flutter-tik-tok-clone-hoo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_tvN1d41QzMFKWS8IDiob_HHYPCbgWFM',
    appId: '1:328461664020:ios:5f67603912da68de2d0c01',
    messagingSenderId: '328461664020',
    projectId: 'flutter-tik-tok-clone-hoo',
    storageBucket: 'flutter-tik-tok-clone-hoo.appspot.com',
    iosClientId: '328461664020-hgnto109ldreurfae2lr5js99qcaultp.apps.googleusercontent.com',
    iosBundleId: 'com.tiktok.tiktokClone',
  );
}
